#ifndef YAHOODATACONNECTION_GLOBAL_H
#define YAHOODATACONNECTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YAHOODATACONNECTION_LIBRARY)
#  define YAHOODATACONNECTIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define YAHOODATACONNECTIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // YAHOODATACONNECTION_GLOBAL_H
